_("&File");
_("&Open Script...");
_("Scripts");
_("Placeholder");
_("Capture &Image...\tF10");
_("Capture &Movie...\tShift+F10");
_("E&xit");
_("&Navigation");
_("Select &Sol\tH");
_("Tour G&uide...");
_("Select &Object...");
_("Goto Object...");
_("&Center Selection\tC");
_("&Go to Selection\tG");
_("&Follow Selection\tF");
_("S&ync Orbit Selection\tY");
_("&Track Selection\tT");
_("Solar System &Browser...");
_("Star B&rowser...");
_("&Eclipse Finder");
_("&Time");
_("10x &Faster\tL");
_("10x &Slower\tK");
_("Free&ze\tSpace");
_("&Real Time\t\\");
_("Re&verse Time\tJ");
_("Set &Time...");
_("Show Local Time");
_("&Render");
_("Select Display Mode...");
_("Toggle Full Screen\tAlt+Enter");
_("View Options...");
_("Locations...");
_("More Stars Visible\t]");
_("Fewer Stars Visible\t[");
_("Auto Magnitude\tCtrl+Y");
_("Star St&yle");
_("&Fuzzy Points");
_("&Points");
_("Scaled &Discs");
_("Star &Color");
_("&Disabled");
_("&Enabled");
_("&Ambient Light");
_("&No");
_("&Weakly");
_("&Moderately");
_("&Texture Resolution");
_("&Low");
_("&Medium");
_("&High");
_("Antialiasing\tCtrl+X");
_("&View");
_("Split &Horizontally\tCtrl+R");
_("Split &Vertically\tCtrl+U");
_("&Delete Active View\tDEL");
_("&Single View\tCtrl+D");
_("Show &Frames");
_("Synchronize &Time");
_("&Bookmarks");
_("&Add Bookmarks...");
_("&Organize Bookmarks...");
_("&Help");
_("Run &Demo");
_("User &Guide");
_("&Controls");
_("&OpenGL Info");
_("&License");
_("&About Celestia");
_("About Celestia");
_("OK");
_("Celestia");
_("Copyright (C) 2001-2017, Celestia Development Team");
_("https://celestiaproject.net/");
_("Celestia is free software and comes with absolutely no warranty.");
_("Authors");
_("Clint Weisbrod");
_("Fridger Schrempp");
_("Christophe Teyssier");
_("Grant Hutchison");
_("Pat Suwalski");
_("Toti");
_("Da Woon Jung");
_("Hank Ramsey");
_("Bob Ippolito");
_("Vincent Giangiulio");
_("Andrew Tribick");
_("Chris Laurel");
_("Select Object");
_("OK");
_("Cancel");
_("Object Name");
_("License");
_("OK");
_("Celestia Controls");
_("OK");
_("OpenGL Driver Info");
_("OK");
_("Set Simulation Time");
_("Time Zone: ");
_("Format: ");
_("Julian Date: ");
_("Set To Current Time");
_("OK");
_("Cancel");
_("Add Bookmark");
_("Name");
_("OK");
_("Cancel");
_("Create in >>");
_("New Folder...");
_("Solar System Browser");
_("OK");
_("Solar System");
_("&Center");
_("&Go To");
_("Solar System Objects");
_("Star Browser");
_("Nearest");
_("Brightest");
_("With planets");
_("&Center");
_("&Go To");
_("&Refresh");
_("OK");
_("Star Search Criteria");
_("Maximum Stars Displayed in List");
_("Tour Guide");
_("OK");
_("Go To");
_("Select your destination:");
_("Go to Object");
_("km");
_("radii");
_("au");
_("Go To");
_("Cancel");
_("Object");
_("Long.");
_("Lat.");
_("Distance");
_("Size:");
_("Frame rate:");
_("Select Display Mode");
_("Resolution");
_("OK");
_("Cancel");
_("View Options");
_("Show");
_("Galaxies");
_("Globulars");
_("Open Clusters");
_("Nebulae");
_("Stars");
_("Planets");
_("Atmospheres");
_("Clouds");
_("Cloud Shadows");
_("Ring Shadows");
_("Eclipse Shadows");
_("Night Side Lights");
_("Comet Tails");
_("Orbits");
_("Markers");
_("Ecliptic Line");
_("Grids");
_("Equatorial");
_("Horizontal");
_("Galactic");
_("Ecliptic");
_("Orbits / Labels");
_("Stars");
_("Planets");
_("Dwarf Planets");
_("Moons");
_("Minor Moons");
_("Asteroids");
_("Comets");
_("Spacecraft");
_("DSO Labels");
_("Galaxies");
_("Globulars");
_("Open Clusters");
_("Nebulae");
_("Constellations");
_("Diagrams");
_("Boundaries");
_("Labels");
_("Latin Names");
_("Information Text");
_("None");
_("Terse");
_("Verbose");
_("Filter Stars");
_("Distance");
_("OK");
_("Cancel");
_("Locations");
_("Cities");
_("Observatories");
_("Landing Sites");
_("Montes (Mountains)");
_("Maria (Seas)");
_("Craters");
_("Valles (Valleys)");
_("Terrae (Land masses)");
_("Volcanoes");
_("Other features");
_("Label Features");
_("OK");
_("Cancel");
_("Show Features");
_("Show Label");
_("Minimum Labeled Feature Size");
_("Add New Bookmark Folder");
_("OK");
_("Cancel");
_("Folder Name");
_("Organize Bookmarks");
_("OK");
_("Cancel");
_("New Folder...");
_("Rename...");
_("Delete");
_("Rename Bookmark or Folder");
_("OK");
_("Cancel");
_("New Name");
_("Eclipse Finder");
_("Compute");
_("Set Date and Go to Planet");
_("Close");
_("From:");
_("To:");
_("On:");
_("Search parameters");
_("Solar Eclipses");
_("Lunar Eclipses");
_("WinLangID");
    _("Jan"), _("Feb"), _("Mar"), _("Apr"), _("May"), _("Jun"),
    _("Jul"), _("Aug"), _("Sep"), _("Oct"), _("Nov"), _("Dec")
