macro(test_case)
  set(trgt ${ARGV0})
  set(libs ${ARGV})
  list(REMOVE_AT libs 0 0)

  add_executable(${trgt} "${trgt}_test.cpp")
  target_include_directories(${trgt} PRIVATE "${CMAKE_SOURCE_DIR}/test/common")
  target_link_libraries(${trgt} PRIVATE celestia catch_main ${libs})
  add_test(${trgt} ${trgt})
  set_target_properties(${trgt} PROPERTIES FOLDER test/unit)
endmacro()
