name: Build

on:
  push:
    branches: [ master ]
    paths: [ src/**, test/**, cmake/**, .github/workflows/ci.yml, CMakeLists.txt ]
  pull_request:
    branches: [ master ]
    paths: [ src/**, test/**, cmake/**, .github/workflows/ci.yml, CMakeLists.txt ]

permissions:
  contents: read
  packages: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  BUILD_TYPE: RelWithDebInfo
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-posix:
    name: "${{matrix.config.os}}"
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-24.04
          avif: ON
          gles: ON
          minaudio: ON
          icu: ON
          qt6: ON
          analysis_artifacts: 1

    runs-on: ${{matrix.config.os}}
    steps:
    - name: 'Install dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-dev \
                                libeigen3-dev \
                                libepoxy-dev \
                                libavcodec-dev \
                                libavformat-dev \
                                libavutil-dev \
                                libswscale-dev \
                                libjpeg-dev \
                                libpng-dev \
                                libglu1-mesa-dev \
                                libfreetype6-dev \
                                libsdl2-dev \
                                libluajit-5.1-dev \
                                libfmt-dev \
                                libicu-dev \
                                gettext \
                                gperf \
                                ninja-build
        if [ "${{matrix.config.qt6}}" = "ON" ]; then
            sudo apt-get install -y qt6-base-dev qt6-base-dev-tools
        fi
        if [ "${{matrix.config.avif}}" = "ON" ]; then
            sudo apt-get install -y libavif-dev
        fi

    - name: 'Checkout source code'
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: 'Configure CMake'
      run: |
        cmake -B ${{github.workspace}}/build                 \
              -G Ninja                                       \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON             \
              -DENABLE_GLES=${{matrix.config.gles}}          \
              -DENABLE_SPICE=OFF                             \
              -DENABLE_TOOLS=OFF                             \
              -DENABLE_TESTS=ON                              \
              -DENABLE_SDL=ON                                \
              -DENABLE_QT6=${{matrix.config.qt6}}            \
              -DENABLE_FFMPEG=ON                             \
              -DENABLE_LIBAVIF=${{matrix.config.avif}}       \
              -DENABLE_MINIAUDIO=${{matrix.config.minaudio}} \
              -DUSE_ICU=${{matrix.config.icu}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: 'Upload autogenerated sources'
      uses: actions/upload-artifact@v7
      if: ${{ success() && matrix.config.analysis_artifacts }}
      with:
        name: celestia-autogenerated-sources
        path: |
          build/compile_commands.json
          build/src/**/*_autogen/**/*.c
          build/src/**/*_autogen/**/*.cc
          build/src/**/*_autogen/**/*.cpp
          build/src/**/*_autogen/**/*.cxx
          build/src/**/*_autogen/**/*.h
          build/src/**/*_autogen/**/*.hh
          build/src/**/*_autogen/**/*.hpp
          build/src/**/*_autogen/**/*.hxx
          build/src/**/*_autogen/**/*.inc
