name: Sonar analysis (push)

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

permissions:
  actions: read
  contents: read

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  sonarscanner:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_repository.full_name == github.event.repository.full_name
    steps:
    - name: 'Install dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-dev \
                                libeigen3-dev \
                                libepoxy-dev \
                                libavcodec-dev \
                                libavformat-dev \
                                libavutil-dev \
                                libswscale-dev \
                                libjpeg-dev \
                                libpng-dev \
                                libglu1-mesa-dev \
                                libfreetype6-dev \
                                libsdl2-dev \
                                libluajit-5.1-dev \
                                libfmt-dev \
                                libicu-dev \
                                ninja-build \
                                qt6-base-dev \
                                qt6-base-dev-tools \
                                gperf \
                                cmake

    - name: 'Checkout source code'
      uses: actions/checkout@v7
      with:
        submodules: true
        repository: ${{ github.event.workflow_run.head_repository.full_name }}
        ref: ${{ github.event.workflow_run.head_branch }}
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: 'Download autogenerated sources'
      uses: actions/download-artifact@v8
      with:
        name: celestia-autogenerated-sources
        path: build
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Analyze push
      uses: SonarSource/sonarqube-scan-action@v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
          -Dsonar.branch.name=${{ github.event.workflow_run.head_branch }}

