name: Sonar analysis (pull request)

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

permissions:
  actions: read
  contents: read
  pull-requests: read

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  sonarscanner:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
    - name: 'Get PR info'
      id: pr-info
      env:
        GH_TOKEN: ${{ github.token }}
        PR_TARGET_REPO: ${{ github.repository }}
        PR_BRANCH: |-
          ${{
            (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
              && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
              || github.event.workflow_run.head_branch
          }}
      run: |
        gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
          --json 'number,headRefOid,headRefName,baseRefName' \
          --jq '"number=\(.number)\nheadRefName=\(.headRefName)\nheadRefOid=\(.headRefOid)\nbaseRefName=\(.baseRefName)"' \
          >> "${GITHUB_OUTPUT}"
    - name: 'Install dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-dev \
                                libeigen3-dev \
                                libepoxy-dev \
                                libavcodec-dev \
                                libavformat-dev \
                                libavutil-dev \
                                libswscale-dev \
                                libjpeg-dev \
                                libpng-dev \
                                libglu1-mesa-dev \
                                libfreetype6-dev \
                                libsdl2-dev \
                                libluajit-5.1-dev \
                                libfmt-dev \
                                libicu-dev \
                                ninja-build \
                                qt6-base-dev \
                                qt6-base-dev-tools \
                                gperf \
                                cmake

    - name: 'Checkout source code'
      uses: actions/checkout@v7
      with:
        submodules: true
        ref: ${{ steps.pr-info.outputs.baseRefName }}
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        allow-unsafe-pr-checkout: true # build is not executed in this workflow

    - name: 'Checkout PR'
      env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ steps.pr-info.outputs.number }}
        PR_TARGET_REPO: ${{ github.repository }}
      run: |
        gh pr checkout ${PR_NUMBER} --repo "${PR_TARGET_REPO}"

    - name: 'Download autogenerated sources'
      uses: actions/download-artifact@v8
      with:
        name: celestia-autogenerated-sources
        path: build
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Analyze pull request
      uses: SonarSource/sonarqube-scan-action@v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.scm.revision=${{ steps.pr-info.outputs.headRefOid }}
          -Dsonar.pullrequest.key=${{ steps.pr-info.outputs.number }}
          -Dsonar.pullrequest.branch=${{ steps.pr-info.outputs.headRefName }}
          -Dsonar.pullrequest.base=${{ steps.pr-info.outputs.baseRefName }}
